insert into Instant (ID, Instant_Name, Set_Name, Rarity, Cost, Color)
values
(1, 'Ancestral Recall', 'Alpha', 'RA', 1, 'U'),
(2, 'Berserk', 'Alpha', 'UC', 1, 'G'),
(3, 'Blaze of Glory', 'Alpha', 'RA', 1, 'W'),
(4, 'Blue Elemental Blast', 'Alpha', 'CM', 1, 'U'),
(5, 'Camouflage', 'Alpha', 'UC', 1, 'G'),
(6, 'Chaoslace', 'Alpha', 'RA', 1, 'R'),
(7, 'Dark Ritaul', 'Alpha', 'CM', 1, 'B'),
(8, 'Death Ward', 'Alpha', 'CM', 1, 'W'),
(9, 'Deathlace', 'Alpha', 'RA', 1, 'B'),
(10, 'Flase Orders', 'Alpha', 'CM', 1, 'R'),
(11, 'Fog', 'Alpha', 'CM', 1, 'G'),
(12, 'Giant Growth', 'Alpha', 'CM', 1, 'G'),
(13, 'Guardian Angel', 'Alpha', 'CM', 1, 'W'),
(14, 'Healing Salve', 'Alpha', 'CM', 1, 'W'),
(15, 'Howl From Beyond', 'Alpha', 'CM', 1, 'B'),
(16, 'Jump', 'Alpha', 'CM', 1, 'U'),
(17, 'Lifelace', 'Alpha', 'RA', 1, 'G'),
(18, 'Lightning Bolt', 'Alpha', 'CM', 1, 'R'),
(19, 'Magical Hack', 'Alpha', 'RA', 1, 'B'),
(20, 'Natural Selection', 'Alpha', 'RA', 1, 'G'),
(21, 'Power Sink', 'Alpha', 'CM', 1, 'U'),
(22, 'Purelace', 'Alpha', 'RA', 1, 'W'),
(23, 'Red Elemental Blast', 'Alpha', 'CM', 1, 'R'),
(24, 'Righteousness', 'Alpha', 'RA', 1, 'W'),
(25, 'Sacrifice', 'Alpha', 'UC', 1, 'B'),
(26, 'Sirens Call', 'Alpha', 'UC', 1, 'U'),
(27, 'Sleight of Mind', 'Alpha', 'RA', 1, 'U'),
(28, 'Spell Blast', 'Alpha', 'CM', 1, 'U'),
(29, 'Swords to Plowshares', 'Alpha', 'UC', 1, 'W'),
(30, 'Thoughtlace', 'Alpha', 'RA', 1, 'B'),
(31, 'Tunnel', 'Alpha', 'UC', 1, 'R'),
(32, 'Twiddle', 'Alpha', 'CM', 1, 'U'),
(33, 'Unsummon', 'Alpha', 'CM', 1, 'U'),
(34, 'Counterspell', 'Alpha', 'UC', 2, 'U'),
(35, 'Disenchant', 'Alpha', 'CM', 2, 'W'),
(36, 'Fork', 'Alpha', 'RA', 2, 'R'),
(37, 'Shatter', 'Alpha', 'CM', 2, 'R'),
(38, 'Simulacrum', 'Alpha', 'UC', 2, 'B'),
(39, 'Terror', 'Alpha', 'CM', 2, 'B'),
(40, 'Word of Command', 'Alpha', 'RA', 2, 'B'),
(41, 'Mana Short', 'Alpha', 'RA', 2, 'U'),
(42, 'Psionic Blast', 'Alpha', 'UC', 2, 'U'),
(43, 'Reverse Damage', 'Alpha', 'RA', 2, 'W');