insert into Enchantment (ID, Enchantment_Name, Set_Name, Rarity, Legendary, Cost, Color)
values
(1, 'Animate Wall', 'Alpha', 'RA', 'No', 1, 'W'),
(2, 'Black Ward', 'Alpha', 'UC', 'No', 1, 'W'),
(3, 'Blue Ward', 'Alpha', 'UC', 'No', 1, 'W'),
(4, 'Burrowing', 'Alpha', 'UC', 'No', 1, 'R'),
(5, 'Consecrate Land', 'Alpha', 'UC', 'No', 1, 'W'),
(6, 'Earthbind', 'Alpha', 'CM', 'No', 1, 'R'),
(7, 'Evil Presence', 'Alpha', 'UC', 'No', 1, 'B'),
(8, 'Fastbond', 'Alpha', 'RA', 'No', 1, 'G'),
(9, 'Firebreathing', 'Alpha', 'CM', 'No', 1, 'R'),
(10, 'Flight', 'Alpha', 'CM', 'No', 1, 'U'),
(11, 'Green Ward', 'Alpha', 'UC', 'No', 1, 'W'),
(12, 'Holy Armor', 'Alpha', 'CM', 'No', 1, 'W'),
(13, 'Holy Strength', 'Alpha', 'CM', 'No', 1, 'W'),
(14, 'Instill Engergy', 'Alpha', 'CM', 'No', 1, 'W'),
(15, 'Lance', 'Alpha', 'UC', 'No', 1, 'W'),
(16, 'Living Artifact', 'Alpha', 'RA', 'No', 1, 'G'),
(17, 'Paralyze', 'Alpha', 'CM', 'No', 1, 'B'),
(18, 'Red Ward', 'Alpha', 'UC', 'No', 1, 'W'),
(19, 'Unholy Strenngth', 'Alpha', 'CM', 'No', 1, 'B'),
(20, 'Weakness', 'Alpha', 'CM', 'No', 1, 'B'),
(21, 'Web', 'Alpha', 'RA', 'No', 1, 'G'),
(22, 'White Ward', 'Alpha', 'UC', 'No', 1, 'W'),
(23, 'Wild Growth', 'Alpha', 'CM', 'No', 1, 'G'),
(24, 'Animate Dead', 'Alpha', 'UC', 'No', 2, 'B'),
(25, 'Aspect Wolf', 'Alpha', 'RA', 'No', 2, 'G'),
(26, 'Bad Moon', 'Alpha', 'RA', 'No', 2, 'B'),
(27, 'Blesing', 'Alpha', 'RA', 'No', 2, 'W'),
(28, 'Circle of Proteection: Blue', 'Alpha', 'CM', 'No', 2, 'W'),
(29, 'Circle of Protection: Green', 'Alpha', 'CM', 'No', 2, 'W'),
(30, 'Circle of Proteciton: Red', 'Alpha', 'CM', 'No', 2, 'W'),
(31, 'Circle of Proteciton: White', 'Alpha', 'CM', 'No', 2, 'W'),
(32, 'Copy Artifact', 'Alpha', 'RA', 'No', 2, 'U'),
(33, 'Creature Bond', 'Alpha', 'CM', 'No', 2, 'U'),
(34, 'Crusade', 'Alpha', 'RA', 'No', 2, 'W'),
(35, 'Deathgrip', 'Alpha', 'UC', 'No', 2, 'B'),
(36, 'Fear', 'Alpha', 'CM', 'No', 2, 'B'),
(37, 'Invisibility', 'Alpha', 'CM', 'No', 2, 'U'),
(38, 'Island Sanctuary', 'Alpha', 'RA', 'No', 2, 'W'),
(39, 'Lifeforce', 'Alpha', 'UC', 'No', 2, 'G'),
(40, 'Lifetap', 'Alpha', 'UC', 'No', 2, 'U'),
(41, 'Phantasmal Terrain', 'Alpha', 'CM', 'No', 2, 'U'),
(42, 'Power Leak', 'Alpha', 'CM', 'No', 2, 'U'),
(43, 'Power Surge', 'Alpha', 'RA', 'No', 2, 'R'),
(44, 'Psychic Venom', 'Alpha', 'CM', 'No', 2, 'U'),
(45, 'Raging River', 'Alpha', 'RA', 'No', 2, 'R'),
(46, 'Regeneration', 'Alpha', 'CM', 'No', 2, 'G'),
(47, 'Smoke', 'Alpha', 'RA', 'No', 2, 'R'),
(48, 'Stasis', 'Alpha', 'RA', 'No', 2, 'U'),
(49, 'Warp Artifact', 'Alpha', 'RA', 'No', 2, 'B'),
(50, 'Farmstead', 'Alpha', 'RA', 'No', 3, 'W'),
(51, 'Feedback', 'Alpha', 'UC', 'No', 3, 'U'),
(52, 'Gloom', 'Alpha', 'UC', 'No', 3, 'B'),
(53, 'Kudzu', 'Alpha', 'RA', 'No', 3, 'G'),
(54, 'Lure', 'Alpha', 'UC', 'No', 3, 'G'),
(55, 'Mana Flare', 'Alpha', 'RA', 'No', 3, 'R'),
(56, 'Wanderlust', 'Alpha', 'UC', 'No', 3, 'G'),
(57, 'Animate Artifact', 'Alpha', 'UC', 'No', 4, 'U'),
(58, 'Castle', 'Alpha', 'UC', 'No', 4, 'W'),
(59, 'Control Magic', 'Alpha', 'UC', 'No', 4, 'U'),
(60, 'Conversion', 'Alpha', 'UC', 'No', 4, 'W'),
(61, 'Cursed Land', 'Alpha', 'UC', 'No', 4, 'B'),
(62, 'Karma', 'Alpha', 'UC', 'No', 4, 'W'),
(63, 'Lich', 'Alpha', 'RA', 'No', 4, 'B'),
(64, 'Living Lands', 'Alpha', 'RA', 'No', 4, 'G'),
(65, 'Manabarbs', 'Alpha', 'RA', 'No', 4, 'R'),
(66, 'Orcish Oriflamme', 'Alpha', 'UC', 'No', 4, 'R'),
(67, 'Pestilence', 'Alpha', 'CM', 'No', 4, 'B'),
(68, 'Steal Artifact', 'Alpha', 'UC', 'No', 4, 'U');