insert into Artifact (ID, Artifact_Name, Set_Name, Rarity, Legendary, Cost)
values 
(1, 'Black Lotus', 'Alpha', 'Rare', 'No', 0),
(2, 'Mox Emerald', 'Alpha', 'Rare', 'No', 0),
(3, 'Mox Jet', 'Alpha', 'Rare', 'No',0),
(4, 'Mox Pearl', 'Alpha', 'Rare', 'No',0),
(5, 'Mox Ruby', 'Alpha', 'Rare', 'No',0),
(6, 'Mox Sapphire', 'Alpha', 'Rare', 'No', 0),
(7, 'Black Vise', 'Alpha', 'Uncommon', 'No', 1),
(8, 'Crystal Rod', 'Alpha', 'Uncommon', 'No',1),
(9, 'Glasses of Urza', 'Alpha', 'Uncommon', 'No',1),
(10, 'Helm of Chatzuk', 'Alpha', 'Rare', 'No',1),
(11, 'Iron Star', 'Alpha', 'Uncommon', 'No', 1),
(12, 'Ivory Cup', 'Alpha', 'Uncommon', 'No', 1),
(13, 'Library of Leng', 'Alpha', 'Uncommon', 'No',1),
(14, 'Mana Vault', 'Alpha', 'Rare', 'No',1),
(15, 'Meekstone', 'Alpha', 'Rare', 'No',1),
(16, 'Sol Ring', 'Alpha', 'Uncommon', 'No', 1),
(17, 'Soul Net', 'Alpha', 'Uncommon', 'No', 1),
(18, 'Throne of Bone', 'Alpha', 'Uncommon', 'No',1),
(19, 'Wooden Sphere', 'Alpha', 'Uncommon', 'No',1),
(20, 'Ankh of Mishra', 'Alpha', 'Rare', 'No',2),
(21, 'Chaos Orb', 'Alpha', 'Rare', 'No', 2),
(22, 'Copper Tablet', 'Alpha', 'Uncommon', 'No', 2),
(23, 'Howling Mine', 'Alpha', 'Rare', 'No',2),
(24, 'Illusionary Mask', 'Alpha', 'Rare', 'No',2),
(25, 'Time Vault', 'Alpha', 'Rare', 'No',2),
(26, 'Winter Orb', 'Alpha', 'Rare', 'No', 2),
(27, 'Basalt Monolith', 'Alpha', 'Uncommon', 'No', 3),
(28, 'Celestial Prism', 'Alpha', 'Uncommon', 'No',3),
(29, 'Disrupting Scepter', 'Alpha', 'Rare', 'No',3),
(30, 'Forcefield', 'Alpha', 'Rare', 'No',3),
(31, 'Sunglasses of Urza', 'Alpha', 'Rare', 'No', 3),
(32, 'Conservator', 'Alpha', 'Uncommon', 'No', 4),
(33, 'Cyclopean Tomb', 'Alpha', 'Rare', 'No',4),
(34, 'Dingus Egg', 'Alpha', 'Rare', 'No',4),
(35, 'Gauntlet of Might', 'Alpha', 'Rare', 'No',4),
(36, 'Icy Manipulator', 'Alpha', 'Uncommon', 'No', 4),
(37, 'Jade Monolith', 'Alpha', 'Rare', 'No', 4),
(38, 'Jayemdae Tome', 'Alpha', 'Rare', 'No',4),
(39, 'Kormus Bell', 'Alpha', 'Rare', 'No', 4),
(40, 'Nevinyrrals Disk', 'Alpha', 'Rare', 'No',4),
(41, 'Rod of Ruin', 'Alpha', 'Uncommon', 'No',4),
(42, 'The Hive', 'Alpha', 'Rare', 'No',5);