insert into Creatures (ID, Creature_Name, Creature_Type, Set_Name, Rarity, Legendary, Color, Power, Toughness, Cost)
values
(2, 'Birds of Paradise', 'Bird', 'Alpha', 'Rare', 'No', 'G', 0, 1, 1),
(3, 'Goblin Balloon Brigade', 'Goblin Warrior', 'Alpha', 'Uncommon', 'No', 'R', 1, 1, 1),
(4, 'Llanowar Elves', 'Elf Druid', 'Alpha', 'Common', 'No', 'G', 1, 1, 1),
(5, 'Merfolk of the Pearl Trident', 'Merfolk', 'Alpha', 'Common', 'No', 'U', 1, 1, 1),
(6, 'Monss Goblin Raiders', 'Goblin', 'Alpha', 'Common', 'No', 'R', 1, 1, 1),
(7, 'Savannah Lions', 'Cat', 'Alpha', 'Rare', 'No', 'W', 2, 1, 1),
(8, 'Scryb Sprites', 'Faerie', 'Alpha', 'Common', 'No', 'G', 1, 1, 1),
(9, 'Shanodin Dryads', 'Nymph Druid', 'Alpha', 'Common', 'No', 'G', 1, 1, 1),
(10, 'Timber Wolves', 'Wolf', 'Alpha', 'Rare', 'No', 'U', 1, 1, 1),
(11, 'Wall of Wood', 'Wall', 'Alpha', 'Common', 'No', 'W', 0, 3, 1),
(12, 'Will-o-the-Wisp', 'Spirit', 'Alpha', 'Rare', 'No', 'B', 0, 1, 1),
(13, 'Black Knight', 'Human Knight', 'Alpha', 'Uncommon', 'No', 'B', 2, 2, 2),
(14, 'Drudge Skeletons', 'Skeleton', 'Alpha', 'Common', 'No', 'B', 1, 1, 2),
(15, 'Elvish Archers', 'Elf Archer', 'Alpha', 'Rare', 'No', 'G', 2, 1, 2),
(16, 'Grizly Bears', 'Bear', 'Alpha', 'Common', 'No', 'G', 2, 2, 2),
(17, 'Ironclaw Orcs', 'Orc', 'Alpha', 'Common', 'No', 'R', 2, 2, 2),
(18, 'Lord of Atlantis', 'Merfolk', 'Alpha', 'Rare', 'No', 'U', 2, 2, 2),
(19, 'Mesa Pegasus', 'Pegasus', 'Alpha', 'Common', 'No', 'W', 1, 1, 2),
(20, 'Nether Shadow', 'Spirit', 'Alpha', 'Rare', 'No', 'B', 1, 1, 2),
(21, 'Rock Hydra', 'Hydra', 'Alpha', 'Rare', 'No', 'R', 0, 0, 2),
(22, 'Samite Healer', 'Human Cleric', 'Alpha', 'Common', 'No', 'W', 1, 1, 2),
(23, 'White Knight', 'Human Knight', 'Alpha', 'Uncommon', 'No', 'W', 2, 2, 2),
(24, 'Dwarven Demolition Team', 'Dwarf', 'Alpha', 'Uncommon', 'No', 'R', 1, 1, 3),
(25, 'Dwarven Warriors', 'Dwarf Warrior', 'Alpha', 'Common', 'No', 'R', 1, 1, 3),
(26, 'Frozen Shade', 'Shade', 'Alpha', 'Common', 'No', 'B', 0, 1, 3),
(27, 'Goblin King', 'Goblin', 'Alpha', 'Rare', 'No', 'R', 2, 2, 3),
(28, 'Granite Gargoyle', 'Gargoyle', 'Alpha', 'Rare', 'No', 'R', 2, 2, 3),
(29, 'Gray Ogre', 'Ogre', 'Alpha', 'Common', 'No', 'R', 2, 2, 3),
(30, 'Hurloon Minotaur', 'Minotaur', 'Alpha', 'Common', 'No', 'R', 2, 3, 3),
(31, 'Hypnotic Specter', 'Specter', 'Alpha', 'Uncommon', 'No', 'B', 2, 2, 3),
(32, 'Ley Druid', 'Human Druid', 'Alpha', 'Uncommon', 'No', 'G', 1, 1, 3),
(33, 'Nettling Imp', 'Imp', 'Alpha', 'Uncommon', 'No', 'B', 1, 1, 2),
(34, 'Orcish Artillery', 'Orc Warrior', 'Alpha', 'Uncommon', 'No', 'R', 1, 3, 3),
(35, 'Pearled Unicorn', 'Unicorn', 'Alpha', 'Common', 'No', 'W', 2, 2, 3),
(36, 'Plague Rats', 'Rat', 'Alpha', 'Common', 'No', 'B', '*', '*', 3),
(37, 'Prodigal Sorcerer', 'Human Wizard', 'Alpha', 'Common', 'No', 'U', 1, 1, 3),
(38, 'Royal Assassin', 'Human Assassin', 'Alpha', 'Rare', 'No', 'B', 1, 1, 3),
(39, 'Scathe Zombies', 'Zombie', 'Alpha', 'Common', 'No', 'B', 2, 2, 3),
(40, 'Sedge Troll', 'Troll', 'Alpha', 'Rare', 'No', 'R', 2, 2, 3),
(41, 'Uthden Troll', 'Troll', 'Alpha', 'Uncommon', 'No', 'R', 2, 2, 3),
(42, 'Verduran Enchantress', 'Human Druid', 'Alpha', 'Rare', 'No', 'G', 0, 2, 3),
(43, 'Wall of Air', 'Wall', 'Alpha', 'Uncommon', 'No', 'U', 1, 5, 3),
(44, 'Wall of Bone', 'Skeleton Wall', 'Alpha', 'Uncommon', 'No', 'B', 1, 4, 3),
(45, 'Wall of Brambles', 'Plant Wall', 'Alpha', 'Uncommon', 'No', 'G', 2, 3, 3),
(46, 'Wall of Fire', 'Wall', 'Alpha', 'Uncommon', 'No', 'R', 0, 5, 3),
(47, 'Wall of Ice', 'Wall', 'Alpha', 'Uncommon', 'No', 'G', 0, 7, 3),
(48, 'Wall of Stone', 'Wall', 'Alpha', 'Uncommon', 'No', 'R', 0, 8, 3),
(49, 'Wall of Water', 'Wall', 'Alpha', 'Uncommon', 'No', 'U', 0, 5, 3),
(50, 'Zombie Master', 'Zombie', 'Alpha', 'Rare', 'No', 'B', 2, 3, 3),
(51, 'Bog Wraith', 'Wraith', 'Alpha', 'Uncommon', 'No', 'B', 3, 3, 4),
(52, 'Clone', 'Shapeshifter', 'Alpha', 'Uncommon', 'No', 'U', 0, 0, 4),
(53, 'Dragon Whelp', 'Dragon', 'Alpha', 'Uncommon', 'No', 'R', 2, 3, 4),
(54, 'Fungusaur', 'Fungus Dinosaur', 'Alpha', 'Rare', 'No', 'G', 2, 2, 4),
(55, 'Giant Spider', 'Spider', 'Alpha', 'Common', 'No', 'G', 2, 4, 4),
(56, 'Hill Giant', 'Giant', 'Alpha', 'Common', 'No', 'R', 3, 3, 4),
(57, 'Jade Statue', 'Artifact', 'Alpha', 'Uncommon', 'No', 'C', 3, 6, 4),
(58, 'Juggernaut', 'Juggernaut', 'Alpha', 'Uncommon', 'No', 'C', 5, 3, 4),
(59, 'Keldon Warlord', 'Human Barbarian', 'Alpha', 'Uncommon', 'No', 'R', '*', '*', 4),
(60, 'Living Wall', 'Wall', 'Alpha', 'Uncommon', 'No', 'C', 0, 6, 4),
(61, 'Northern Paladin', 'Human Knight', 'Alpha', 'Rare', 'No', 'W', 3, 3, 4),
(62, 'Phantasmal Forces', 'Illusion', 'Alpha', 'Uncommon', 'No', 'U', 4, 1, 4),
(63, 'Phantom Monster', 'Illusion', 'Alpha', 'Uncommon', 'No', 'U', 3, 3, 4),
(64, 'Roc of Kher Ridges', 'Bird', 'Alpha', 'Rare', 'No', 'R', 3, 3, 4),
(65, 'Scavenging Ghoul', 'Zombie', 'Alpha', 'Uncommon', 'No', 'B', 2, 2, 4),
(66, 'Stone Giant', 'Giant', 'Alpha', 'Uncommon', 'No', 'R', 3, 4, 4),
(67, 'Wall of Swords', 'Wall', 'Alpha', 'Uncommon', 'No', 'W', 3, 5, 4),
(68, 'War Mammoth', 'Elephant', 'Alpha', 'Common', 'No', 'G', 3, 3, 4),
(69, 'Air Elemental', 'Elemental', 'Alpha', 'Uncommon', 'No', 'U', 4, 4, 5),
(70, 'Cockatrice', 'Cockatrice', 'Alpha', 'Rare', 'No', 'G', 2, 4, 5),
(71, 'Earth Elemental', 'Elemental', 'Alpha', 'Uncommon', 'No', 'R', 2, 2, 5),
(72, 'Fire Elemental', 'Elemental', 'Alpha', 'Uncommon', 'No', 'R', 5, 4, 5),
(73, 'Ironroot Treefolk', 'Treefolk', 'Alpha', 'Common', 'No', 'G', 3, 5, 5),
(74, 'Pirate Ship', 'Human Pirate', 'Alpha', 'Rare', 'No', 'U', 4, 3, 5),
(75, 'Sengir Vampire', 'Vampire', 'Alpha', 'Uncommon', 'No', 'B', 4, 4, 5),
(76, 'Serra Angel', 'Angel', 'Alpha', 'Uncommon', 'No', 'W', 4, 4, 5),
(77, 'Thicket Basilisk', 'Basilisk', 'Alpha', 'Uncommon', 'No', 'G', 2, 4, 5),
(78, 'Two-Headed Giant of Foriys', 'Giant', 'Alpha', 'Rare', 'No', 'R', 4, 4, 5),
(79, 'Vesuvan Doppleganger', 'Shapeshifter', 'Alpha', 'Rare', 'No', 'U', 0, 0, 5),
(80, 'Veteran Bodyguard', 'Human', 'Alpha', 'Rare', 'No', 'W', 2, 5, 5),
(81, 'Water Elemental', 'Elemental', 'Alpha', 'Uncommon', 'No', 'U', 5, 4, 5),
(82, 'Clockwork Beast', 'Artifact Beast', 'Alpha', 'Rare', 'No', 'C', 0, 4, 6),
(83, 'Craw Wurm', 'Wurm', 'Alpha', 'Common', 'No', 'G', 6, 4, 6),
(84, 'Demonic Hordes', 'Demon', 'Alpha', 'Rare', 'No', 'B', 5, 5, 6),
(85, 'Force of Nature', 'Elemental', 'Alpha', 'Rare', 'No', 'G', 8, 8, 6),
(86, 'Gaeas Liege', 'Avatar', 'Alpha', 'Rare', 'No', 'G', '*', '*', 6),
(87, 'Mahamoti Djinn', 'Djinn', 'Alpha', 'Rare', 'No', 'U', 5, 6, 6),
(88, 'Nightmare', 'Nightmare Horse', 'Alpha', 'Rare', 'No', 'B', '*', '*', 6),
(89, 'Obsianus Golem', 'Golem', 'Alpha', 'Uncommon', 'No', 'C', 4, 6, 6),
(90, 'Personal Incarnation', 'Avatar Incarnation', 'Alpha', 'Rare', 'No', 'W', 6, 6, 6),
(91, 'Sea Serpent', 'Serpent', 'Alpha', 'Common', 'No', 'U', 5, 5, 6),
(92, 'Shivan Dragon', 'Dragon', 'Alpha', 'Rare', 'No', 'R', 5, 5, 6),
(93, 'Lord of the Pit', 'Demon', 'Alpha', 'Rare', 'No', 'B', 7, 7, 6);