insert into Sorcery (ID, Sorcery_Name, Set_Name, Rarity, Cost, Color)
values
(1, 'Contract from Below', 'Alpha', 'RA', 1, 'B'),
(2, 'Disintegrate', 'Alpha', 'CM', 1, 'R'),
(3, 'Earthquake', 'Alpha', 'RA', 1, 'R'),
(4, 'Fireball', 'Alpha', 'CM', 1, 'R'),
(5, 'Hurricane', 'Alpha', 'UC', 1, 'G'),
(6, 'Mind Twist', 'Alpha', 'RA', 1, 'B'),
(7, 'Raise Dead', 'Alpha', 'CM', 1, 'B'),
(8, 'Stream of Life', 'Alpha', 'CM', 1, 'G'),
(9, 'Balance', 'Alpha', 'RA', 2, 'W'),
(10, 'Braingeyser', 'Alpha', 'RA', 2, 'U'),
(11, 'Channel', 'Alpha', 'UC', 2, 'G'),
(12, 'Demonic Tutor', 'Alpha', 'UC', 2, 'B'),
(13, 'Drain Lfe', 'Alpha', 'CM', 2, 'B'),
(14, 'Drain Power', 'Alpha', 'RA', 2, 'U'),
(15, 'Regrowth', 'Alpha', 'UC', 2, 'G'),
(16, 'Sinkhole', 'Alpha', 'CM', 2, 'B'),
(17, 'Time Walk', 'Alpha', 'RA', 2, 'U'),
(18, 'Darkpact', 'Alpha', 'RA', 3, 'B'),
(19, 'Demonic Attorney', 'Alpha', 'RA', 3, 'B'),
(20, 'Ice Storm', 'Alpha', 'UC', 3, 'G'),
(21, 'Stone Rain', 'Alpha', 'CM', 3, 'R'),
(22, 'Timetwister', 'Alpha', 'RA', 3, 'U'),
(23, 'Tranquility', 'Alpha', 'CM', 3, 'G'),
(24, 'Volcanic Eruption', 'Alpha', 'RA', 3, 'U'),
(25, 'Wheel of Fortune', 'Alpha', 'RA', 3, 'R'),
(26, 'Armageddon', 'Alpha', 'RA', 4, 'W'),
(27, 'Flashfires', 'Alpha', 'UC', 4, 'R'),
(28, 'Resurreection', 'Alpha', 'UC', 4, 'W'),
(29, 'Tsunami', 'Alpha', 'UC', 4, 'G'),
(30, 'Wrath of God', 'Alpha', 'RA', 4, 'W');